name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize] 
    
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    services:
      h2:
        image: oscarfonts/h2
        ports:
          - 1521:1521
        options: >-
          --health-cmd "java -cp /opt/h2/bin/h2*.jar org.h2.tools.Server -ifNotExists -web -webAllowOthers -tcp -tcpAllowOthers -baseDir /h2-data"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: actions checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Initialize Database
      run: java -cp your-application.jar:./h2/bin/h2*.jar org.h2.tools.RunScript -script ./resources/sql/data.sql -url jdbc:h2:file:./productsDB -user sa -password ""
        
    - name: Install Dependencies
      run: 'mvn compile'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test
