name: Continuous Integration
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
